apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels: {{- include "shopmesh.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/part-of: shopmesh
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image }}
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef: { name: shopmesh-secrets, key: RABBITMQ_USER }
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef: { name: shopmesh-secrets, key: RABBITMQ_PASSWORD }
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - { name: amqp, port: 5672 }
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
spec:
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - { name: http, port: 15672 }
